# Generated by Django 6.0.3 on 2026-03-25 20:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('publication_year', models.PositiveIntegerField(blank=True, help_text='Year the book was first published (optional).', null=True)),
                ('isbn', models.CharField(blank=True, help_text='ISBN-10 or ISBN-13 (optional, not strictly validated).', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description / blurb.')),
                ('cover_image_url', models.URLField(blank=True, help_text='Optional URL to a cover image.')),
                ('library_code', models.CharField(blank=True, help_text='Internal library identifier or call number (optional).', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title', 'author'],
                'indexes': [models.Index(fields=['title'], name='libraryboxd_title_824fc1_idx'), models.Index(fields=['author'], name='libraryboxd_author_82b9aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_private', models.BooleanField(default=False, help_text="If enabled, this user's profile and activity may be limited in visibility.")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite_books', models.ManyToManyField(blank=True, help_text='Optional set of favorite books for this user.', related_name='fans', to='libraryboxd.book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_read', models.DateField(blank=True, help_text='Optional date when the book was read/finished.', null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], help_text="1–5 stars; optional if user doesn't want to rate.", null=True)),
                ('review', models.TextField(blank=True, help_text='Optional review or comments about the book.')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', help_text='Visibility of this entry (future feature; currently all treated as internal).', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this entry was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this entry was last updated.')),
                ('is_active', models.BooleanField(default=True, help_text='Admins can deactivate entries instead of deleting (optional moderation tool).')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_entries', to='libraryboxd.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_read', '-created_at'],
                'indexes': [models.Index(fields=['user', 'book'], name='libraryboxd_user_id_7700db_idx'), models.Index(fields=['book'], name='libraryboxd_book_id_06c446_idx'), models.Index(fields=['user'], name='libraryboxd_user_id_96b8d5_idx')],
            },
        ),
    ]
